#!/usr/bin/env python
# Copyright 2015 Richard Hawkins
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import os
import sys

from swift.common.ring import Ring
from swift.common.utils import split_path

from stat import S_IFDIR, S_IFREG
from fuse import FUSE, FuseOSError, Operations

import requests

class SAIOFuse(Operations):

    # Helper methods
    # ==============

    def _list_accounts(self):
        return ['AUTH_test']

    def _list_containers(self, account):
        return ['saiof_test_read_access']

    def _list_objects(self, account, container):
        return ['object']

    # Filesystem methods
    # ==================

    def getattr(self, path, fh=None):
        mode = S_IFREG | 0444
        nlink = 1

        if path in '/v1/AUTH_test/saiof_test_read_access':
            mode = S_IFDIR | 0555
            nlink = 2

        attr = {
            'st_atime': 1420658919.81,
            'st_ctime': 1420658915.13,
            'st_gid': 1000,
            'st_mode': mode,
            'st_mtime': 1420658915.13,
            'st_nlink': nlink,
            'st_size': 15,
            'st_uid': 1000,
        }

        return attr

    def readdir(self, path, fh):
        account = None
        container = None
        obj = None

        if path != '/' and path != '/v1':
            account, container, obj = split_path(path[3:], 1, 3)

        listing = []
        if account is None and path == '/':
            listing = ['v1']
        elif account is None and path == '/v1':
            listing = self._list_accounts()
        elif container is None and obj is None:
            listing = self._list_containers(account)
        elif obj is None:
            listing = self._list_objects(account, container)

        dirents = ['.', '..']
        dirents.extend(listing)
        for r in dirents:
            yield r


def main(mountpoint):
    FUSE(SAIOFuse(), mountpoint, foreground=True)


if __name__ == '__main__':
    main(sys.argv[1])
